'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls.Rules

    Partial Public Class Rules

        '''<summary>
        '''hdnRandomTeam1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnRandomTeam1 As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdnRandomTeam2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnRandomTeam2 As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''divRules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divRules As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litCompetitionDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCompetitionDescription As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
