'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls

    Partial Public Class LoginInformation

        '''<summary>
        '''lblCurrentCompetition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentCompetition As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLoginInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoginInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hypUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypUser As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''btnLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
