'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls

    Partial Public Class Navigation

        '''<summary>
        '''liMessageboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liMessageboard As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hypEditProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypEditProfile As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''liAdministration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liAdministration As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''liProcessMatches control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liProcessMatches As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''liMatchListAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liMatchListAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''liPaymentCreditList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liPaymentCreditList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''liCompetitionList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liCompetitionList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
