'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls.Twitter

	Partial Public Class TwitterFeed

		'''<summary>
		'''divTwitter control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents divTwitter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

		'''<summary>
		'''hypTwitter control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents hypTwitter As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''imgTwitpic control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgTwitpic As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblScreenName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblScreenName As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lstTimeline control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lstTimeline As Global.System.Web.UI.WebControls.ListView

		'''<summary>
		'''hypTwitter2 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents hypTwitter2 As Global.System.Web.UI.WebControls.HyperLink
	End Class
End Namespace
