// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Predictathon.Domain.Entities;

namespace Predictathon.Infrastructure.Persistence;

public partial class ApplicationDbContext : GenericDbContext<ApplicationDbContext>
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Announcement> Announcement => Set<Announcement>();

    public virtual DbSet<Competition> Competition => Set<Competition>();

    public virtual DbSet<ErrorLog> ErrorLog => Set<ErrorLog>();

    public virtual DbSet<FixtureChangeProposal> FixtureChangeProposal => Set<FixtureChangeProposal>();

    public virtual DbSet<HallOfFame> HallOfFame => Set<HallOfFame>();

    public virtual DbSet<Match> Match => Set<Match>();

    public virtual DbSet<Message> Message => Set<Message>();

    public virtual DbSet<MessageReaction> MessageReaction => Set<MessageReaction>();

    public virtual DbSet<MessageThread> MessageThread => Set<MessageThread>();

    public virtual DbSet<MessageThreadRead> MessageThreadRead => Set<MessageThreadRead>();

    public virtual DbSet<PaymentCredit> PaymentCredit => Set<PaymentCredit>();

    public virtual DbSet<Prediction> Prediction => Set<Prediction>();

    public virtual DbSet<PredictionHistory> PredictionHistory => Set<PredictionHistory>();

    public virtual DbSet<Team> Team => Set<Team>();

    public virtual DbSet<TeamCompetition> TeamCompetition => Set<TeamCompetition>();

    public virtual DbSet<Transaction> Transaction => Set<Transaction>();

    public virtual DbSet<UserCompetition> UserCompetition => Set<UserCompetition>();

    public virtual DbSet<UserCompetitionLeagueHistory> UserCompetitionLeagueHistory => Set<UserCompetitionLeagueHistory>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Announcement>(entity =>
        {
            entity.Property(e => e.Content).HasMaxLength(2000);
            entity.Property(e => e.Severity)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Info", "DF_Announcement_Severity");
            entity.Property(e => e.ExpiryDateTimeUtc).HasColumnType("datetime");
            entity.Property(e => e.CreatedAtUtc)
                .HasDefaultValueSql("sysutcdatetime()", "DF_Announcement_CreatedAtUtc")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Competition>(entity =>
        {
            entity.Property(e => e.CompetitionID).HasDefaultValueSql("newid()");
            entity.Property(e => e.CompetitionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EntranceFee).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.ExternalApiCompetitionCode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ImageFilename)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.Information).IsUnicode(false);
            entity.Property(e => e.PayPalPaymentAvailable).HasDefaultValue(true, "DF_Competition_PayPalPaymentAvailable");
            entity.Property(e => e.AllowTwoPointers).HasDefaultValue(true, "DF_Competition_AllowTwoPointers");
        });

        modelBuilder.Entity<ErrorLog>(entity =>
        {
            entity.Property(e => e.Level).HasMaxLength(128);
        });

        modelBuilder.Entity<FixtureChangeProposal>(entity =>
        {
            entity.HasIndex(e => e.MatchID, "IX_FixtureChangeProposal_MatchID_Pending")
                .IsUnique()
                .HasFilter("([Status]='Pending')");

            entity.Property(e => e.DetectedAtUtc)
                .HasDefaultValueSql("sysutcdatetime()", "DF_FixtureChangeProposal_DetectedAtUtc")
                .HasColumnType("datetime");
            entity.Property(e => e.PreviousMatchDateTime).HasColumnType("datetime");
            entity.Property(e => e.ProposedMatchDateTime).HasColumnType("datetime");
            entity.Property(e => e.ResolvedAtUtc).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending", "DF_FixtureChangeProposal_Status");

            entity.HasOne(d => d.Match).WithMany(p => p.FixtureChangeProposal)
                .HasForeignKey(d => d.MatchID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FixtureChangeProposal_Match");
        });

        modelBuilder.Entity<HallOfFame>(entity =>
        {
            entity.Property(e => e.HallOfFameID).ValueGeneratedNever();
            entity.Property(e => e.CompetitionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ImageFilename)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.SecondPlace)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ThirdPlace)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Winner)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Competition).WithMany(p => p.HallOfFame)
                .HasForeignKey(d => d.CompetitionID)
                .HasConstraintName("FK_HallOfFame_Competition");
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasIndex(e => e.ExternalMatchID, "IX_Match_ExternalMatchID")
                .IsUnique()
                .HasFilter("([ExternalMatchID] IS NOT NULL)");

            entity.Property(e => e.MatchID).ValueGeneratedNever();
            entity.Property(e => e.AwayTeamTBC)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.HomeTeamTBC)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MatchDateTime).HasColumnType("datetime");

            entity.HasOne(d => d.AwayTeam).WithMany(p => p.MatchAwayTeam)
                .HasForeignKey(d => d.AwayTeamID)
                .HasConstraintName("FK_Match_AwayTeam");

            entity.HasOne(d => d.Competition).WithMany(p => p.Match)
                .HasForeignKey(d => d.CompetitionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_Competition");

            entity.HasOne(d => d.HomeTeam).WithMany(p => p.MatchHomeTeam)
                .HasForeignKey(d => d.HomeTeamID)
                .HasConstraintName("FK_Match_HomeTeam");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasIndex(e => e.MessageThreadID, "IX_Message_MessageThreadID");

            entity.Property(e => e.MessageID).ValueGeneratedNever();
            entity.Property(e => e.MessageDateTime)
                .HasDefaultValueSql("getdate()", "DF_Message_MessageDateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.YouTubeVideoID)
                .HasMaxLength(11)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.MessageThread).WithMany(p => p.Message)
                .HasForeignKey(d => d.MessageThreadID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Message_MessageThread");
        });

        modelBuilder.Entity<MessageReaction>(entity =>
        {
            entity.HasKey(e => e.MessageReactionID).IsClustered(false);

            entity.HasIndex(e => new { e.MessageID, e.CreationDate }, "IX_MessageReaction_MessageID");

            entity.Property(e => e.MessageReactionID).ValueGeneratedNever();
            entity.Property(e => e.CreationDate).HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.ReactionName).HasMaxLength(200);

            entity.HasOne(d => d.Message).WithMany(p => p.MessageReaction)
                .HasForeignKey(d => d.MessageID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MessageReaction_Message");
        });

        modelBuilder.Entity<MessageThread>(entity =>
        {
            entity.Property(e => e.MessageThreadID).ValueGeneratedNever();
            entity.Property(e => e.StartedDateTime)
                .HasDefaultValueSql("getdate()", "DF_MessageThread_StartedDateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.ThreadSubject)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<MessageThreadRead>(entity =>
        {
            entity.HasIndex(e => new { e.UserID, e.MessageThreadID }, "IX_MessageThreadRead_UserID_MessageThreadID").IsUnique();

            entity.Property(e => e.LastReadDateTime).HasColumnType("datetime");

            entity.HasOne(d => d.MessageThread).WithMany(p => p.MessageThreadRead)
                .HasForeignKey(d => d.MessageThreadID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MessageThreadRead_MessageThread");
        });

        modelBuilder.Entity<PaymentCredit>(entity =>
        {
            entity.Property(e => e.PaymentCreditID).ValueGeneratedNever();
            entity.Property(e => e.ExpectedUsername)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IssueDate).HasColumnType("datetime");
            entity.Property(e => e.UniquePaymentCode)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.ForCompetition).WithMany(p => p.PaymentCredit)
                .HasForeignKey(d => d.ForCompetitionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentCredit_Competition");
        });

        modelBuilder.Entity<Prediction>(entity =>
        {
            entity.HasIndex(e => new { e.MatchID, e.UserID, e.HomeTeamGoals, e.AwayTeamGoals, e.Score, e.GoalDifference }, "IX_Prediction_MatchID_Included");

            entity.HasIndex(e => e.UserID, "IX_Prediction_UserID_Included");

            entity.HasIndex(e => new { e.MatchID, e.UserID }, "UK_Prediction_MatchID_UserID").IsUnique();

            entity.Property(e => e.PredictionID).ValueGeneratedNever();

            entity.HasOne(d => d.Match).WithMany(p => p.Prediction)
                .HasForeignKey(d => d.MatchID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Prediction_Match");
        });

        modelBuilder.Entity<PredictionHistory>(entity =>
        {
            entity.HasIndex(e => e.PredictionID, "IX_PredictionHistory_PredictionID");

            entity.Property(e => e.PredictionDateTime)
                .HasDefaultValueSql("getdate()", "DF_PredictionHistory_PredictionDateTime")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.Property(e => e.TeamID).ValueGeneratedNever();
            entity.Property(e => e.ExternalApiCode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ImageName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ShortName)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TeamName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TeamCompetition>(entity =>
        {
            entity.Property(e => e.TeamCompetitionID).ValueGeneratedNever();

            entity.HasOne(d => d.Competition).WithMany(p => p.TeamCompetition)
                .HasForeignKey(d => d.CompetitionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeamCompetition_Competition");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamCompetition)
                .HasForeignKey(d => d.TeamID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeamCompetition_Team");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.Property(e => e.TransactionID).ValueGeneratedNever();
            entity.Property(e => e.ActualPaymentAmount)
                .HasDefaultValue(0.00m, "DF_Transaction_ActualPaymentAmount")
                .HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Amount).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Comments)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmailAddress)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.Forenames)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.PayPalFee).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.PayPalTransactionID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Surname)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TransactionDateTime).HasColumnType("datetime");
            entity.Property(e => e.TransactionStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Username)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Competition).WithMany(p => p.Transaction)
                .HasForeignKey(d => d.CompetitionID)
                .HasConstraintName("FK_Transaction_Competition");

            entity.HasOne(d => d.UserCompetition).WithMany(p => p.Transaction)
                .HasForeignKey(d => d.UserCompetitionID)
                .HasConstraintName("FK_Transaction_UserCompetition1");
        });

        modelBuilder.Entity<UserCompetition>(entity =>
        {
            entity.Property(e => e.UserCompetitionID).ValueGeneratedNever();
            entity.Property(e => e.AmountPaid).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LastEmailReminderSent).HasColumnType("datetime");
            entity.Property(e => e.PaymentProvider)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Competition).WithMany(p => p.UserCompetition)
                .HasForeignKey(d => d.CompetitionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserCompetition_Competition");
        });

        modelBuilder.Entity<UserCompetitionLeagueHistory>(entity =>
        {
            entity.Property(e => e.UserCompetitionLeagueHistoryID).HasDefaultValueSql("newid()", "DF_Table_1_LeagueHistoryID");
            entity.Property(e => e.AverageGoalDifference).HasColumnType("decimal(9, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
