'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls.Message

    Partial Public Class NewMessage

        '''<summary>
        '''txtMessageContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMessageContent As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAttachment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rbNone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbNone As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbUploadImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbUploadImage As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbYouTubeVideoLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbYouTubeVideoLink As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divYouTubeVideoLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divYouTubeVideoLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblYouTubeVideoLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblYouTubeVideoLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtYouTubeVideoLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtYouTubeVideoLink As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divUploadFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUploadFile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblUploadFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUploadFile As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FileUpload1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''spnUploadFromURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnUploadFromURL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblUploadFromURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUploadFromURL As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtUploadFromURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUploadFromURL As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
