export async function getLeague() {
    await new Promise((resolve) => setTimeout(resolve, 500));

    return {
        results: [
            {
                pos: 1,
                userId: "BhtjCW",
                username: "MakeTheWCGrateAgen",
                three: 7,
                two: 1,
                one: 4,
                zero: 3,
                missed: 1,
                points: 37,
                agd: -1.97
            },
            {
                pos: 2,
                userId: "E5Bkln",
                username: "Masterblast",
                three: 5,
                two: 1,
                one: 8,
                zero: 2,
                missed: 0,
                points: 35,
                agd: -2.0
            },
            {
                pos: 3,
                userId: "yoky2L",
                username: "Scarlett13",
                three: 3,
                two: 5,
                one: 5,
                zero: 3,
                missed: 0,
                points: 34,
                agd: -1.97
            },
            {
                pos: 4,
                userId: "Hgj5qT",
                username: "Mitchell",
                three: 4,
                two: 4,
                one: 4,
                zero: 4,
                missed: 0,
                points: 34,
                agd: -2.06
            },
            {
                pos: 5,
                userId: "WLgQdU",
                username: "Nugsson",
                three: 4,
                two: 2,
                one: 6,
                zero: 4,
                missed: 0,
                points: 32,
                agd: -1.83
            },
            {
                pos: 6,
                userId: "c1BToh",
                username: "DarkishJungle",
                three: 5,
                two: 0,
                one: 7,
                zero: 4,
                missed: 0,
                points: 32,
                agd: -2.0
            },
            {
                pos: 7,
                userId: "JOMrzg",
                username: "JP",
                three: 4,
                two: 1,
                one: 8,
                zero: 3,
                missed: 0,
                points: 32,
                agd: -2.06
            },
            {
                pos: 8,
                userId: "pWAk5n",
                username: "Luther Blissett",
                three: 5,
                two: 1,
                one: 4,
                zero: 6,
                missed: 0,
                points: 31,
                agd: -2.0
            },
            {
                pos: 9,
                userId: "tFGyCc",
                username: "No Drawers",
                three: 3,
                two: 2,
                one: 7,
                zero: 4,
                missed: 0,
                points: 30,
                agd: -2.0
            },
            {
                pos: 10,
                userId: "Bow4Ac",
                username: "klasing",
                three: 2,
                two: 3,
                one: 8,
                zero: 3,
                missed: 0,
                points: 30,
                agd: -2.11
            },
            {
                pos: 11,
                userId: "TmGUxX",
                username: "wiztipskimor",
                three: 1,
                two: 4,
                one: 8,
                zero: 3,
                missed: 30,
                points: 29,
                agd: -1.92
            },
            {
                pos: 12,
                userId: "s1fUWr",
                username: "Fe",
                three: 2,
                two: 2,
                one: 9,
                zero: 3,
                missed: 0,
                points: 29,
                agd: -1.94
            },
            {
                pos: 13,
                userId: "3hovBm",
                username: "Mubba Liscious",
                three: 5,
                two: 0,
                one: 4,
                zero: 7,
                missed: 0,
                points: 29,
                agd: -1.97
            },
            {
                pos: 14,
                userId: "5dbIhZ",
                username: "bwozere",
                three: 4,
                two: 2,
                one: 3,
                zero: 5,
                missed: 2,
                points: 29,
                agd: -2.09
            },
            {
                pos: 15,
                userId: "A7glAr",
                username: "goonergirl",
                three: 5,
                two: 2,
                one: 8,
                zero: 8,
                missed: 3,
                points: 27,
                agd: -2.0
            },
            {
                pos: 16,
                userId: "pZnyw2",
                username: "Gatesy",
                three: 3,
                two: 2,
                one: 4,
                zero: 7,
                missed: 0,
                points: 27,
                agd: -1.89
            },
            {
                pos: 17,
                userId: "qnfZp8",
                username: "NickTheSnick",
                three: 3,
                two: 2,
                one: 4,
                zero: 7,
                missed: 0,
                points: 27,
                agd: -2.03
            },
            {
                pos: 18,
                userId: "78PDYq",
                username: "Taffyboy",
                three: 2,
                two: 5,
                one: 1,
                zero: 7,
                missed: 1,
                points: 27,
                agd: -2.4
            },
            {
                pos: 19,
                userId: "ud9taM",
                username: "Phoenixkeeper",
                three: 4,
                two: 0,
                one: 4,
                zero: 7,
                missed: 1,
                points: 26,
                agd: -2.0
            },
            {
                pos: 20,
                userId: "Np7AZT",
                username: "JB82",
                three: 4,
                two: 0,
                one: 4,
                zero: 6,
                missed: 2,
                points: 26,
                agd: -2.24
            },
            {
                pos: 21,
                userId: "stSz7T",
                username: "stu",
                three: 2,
                two: 1,
                one: 8,
                zero: 5,
                missed: 0,
                points: 26,
                agd: -2.22
            },
            {
                pos: 22,
                userId: "UV4AjL",
                username: "Chris",
                three: 0,
                two: 4,
                one: 8,
                zero: 3,
                missed: 1,
                points: 26,
                agd: -2.46
            },
            {
                pos: 23,
                userId: "uySCEM",
                username: "Owlwoman",
                three: 3,
                two: 1,
                one: 4,
                zero: 7,
                missed: 1,
                points: 25,
                agd: -1.97
            },
            {
                pos: 24,
                userId: "Zap6de",
                username: "LewisQuicky",
                three: 2,
                two: 2,
                one: 4,
                zero: 8,
                missed: 0,
                points: 24,
                agd: -2.06
            },
            {
                pos: 25,
                userId: "3lek59",
                username: "Suzan Ham",
                three: 3,
                two: 1,
                one: 3,
                zero: 9,
                missed: 0,
                points: 24,
                agd: -2.08
            },
            {
                pos: 26,
                userId: "TjjaGO",
                username: "weecalf",
                three: 2,
                two: 2,
                one: 3,
                zero: 9,
                missed: 0,
                points: 23,
                agd: -2.11
            },
            {
                pos: 27,
                userId: "nIErfW",
                username: "binhnq",
                three: 3,
                two: 2,
                one: 9,
                zero: 4,
                missed: 8,
                points: 22,
                agd: -2.07
            },
            {
                pos: 28,
                userId: "IipoY3",
                username: "Gunners forever",
                three: 1,
                two: 2,
                one: 5,
                zero: 8,
                missed: 0,
                points: 22,
                agd: -2.0
            },
            {
                pos: 29,
                userId: "GlUo3H",
                username: "Rice Rice Baby",
                three: 1,
                two: 3,
                one: 2,
                zero: 0,
                missed: 0,
                points: 21,
                agd: -2.17
            },
            {
                pos: 30,
                userId: "nXtdSK",
                username: "MFFootbot 2026",
                three: 2,
                two: 1,
                one: 2,
                zero: 0,
                missed: 1,
                points: 20,
                agd: -2.11
            },
            {
                pos: 31,
                userId: "Gxer7Z",
                username: "AVermouthWanker",
                three: 1,
                two: 2,
                one: 3,
                zero: 0,
                missed: 0,
                points: 20,
                agd: -2.5
            },
            {
                pos: 32,
                userId: "9BtYLO",
                username: "swingitinthemixer",
                three: 3,
                two: 1,
                one: 7,
                zero: 5,
                missed: 0,
                points: 18,
                agd: -1.97
            },
            {
                pos: 33,
                userId: "hCfqF1",
                username: "CardinalGareth",
                three: 1,
                two: 0,
                one: 5,
                zero: 0,
                missed: 0,
                points: 18,
                agd: -2.25
            },
            {
                pos: 34,
                userId: "eS4Skd",
                username: "LisaBadger",
                three: 1,
                two: 0,
                one: 0,
                zero: 3,
                missed: 2,
                points: 13,
                agd: -2.38
            }
        ]
    };
}
