'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.Statistics
    
    Partial Public Class AllTime
        
        '''<summary>
        '''HighestAllTimeScore1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HighestAllTimeScore1 As Global.Predictathon.UserControls.Statistics.HighestAllTimeScore
        
        '''<summary>
        '''HighestAverageScore1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HighestAverageScore1 As Global.Predictathon.UserControls.Statistics.HighestAverageScore
        
        '''<summary>
        '''HighestPercentageCorrect1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HighestPercentageCorrect1 As Global.Predictathon.UserControls.Statistics.HighestPercentageCorrect
        
        '''<summary>
        '''CompetitionWinners1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompetitionWinners1 As Global.Predictathon.UserControls.Statistics.CompetitionWinners
        
        '''<summary>
        '''MostPredictions1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MostPredictions1 As Global.Predictathon.UserControls.Statistics.MostPredictions
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master,Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
