'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.Statistics
    
    Partial Public Class CurrentCompetition
        
        '''<summary>
        '''BestPredictions1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BestPredictions1 As Global.Predictathon.UserControls.Statistics.BestPredictions
        
        '''<summary>
        '''MostPredictableMatches control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MostPredictableMatches As Global.Predictathon.UserControls.Statistics.PredictableMatches
        
        '''<summary>
        '''LeastPredictableMatches control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LeastPredictableMatches As Global.Predictathon.UserControls.Statistics.PredictableMatches
        
        '''<summary>
        '''PredictableTeams1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PredictableTeams1 As Global.Predictathon.UserControls.Statistics.PredictableTeams
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master,Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
