'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls.Statistics
    
    Partial Public Class HighestPercentageCorrect
        
        '''<summary>
        '''lblGridTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGridTitle As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''gvPercentageCorrect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvPercentageCorrect As Global.Predictathon.Web.UI.WebControls.GridView
    End Class
End Namespace
