'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.Team

    Partial Public Class TeamDetail

        '''<summary>
        '''divTeamStatistics control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTeamStatistics As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgTeam As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblTeamName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTeamName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblGoalsFor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGoalsFor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblGoalsAgainst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGoalsAgainst As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trAverageGoalsForHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAverageGoalsForHome As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAverageGoalsForHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsForHome As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAverageGoalsForHomeValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsForHomeValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trAverageGoalsAgainstHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAverageGoalsAgainstHome As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAverageGoalsAgainstHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsAgainstHome As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAverageGoalsAgainstHomeValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsAgainstHomeValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trAverageGoalsForAway control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAverageGoalsForAway As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAverageGoalsForAway control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsForAway As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAverageGoalsForAwayValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsForAwayValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trAverageGoalsAgainstAway control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAverageGoalsAgainstAway As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAverageGoalsAgainstAway control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsAgainstAway As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAverageGoalsAgainstAwayValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsAgainstAwayValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trAverageGoalsForTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAverageGoalsForTotal As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAverageGoalsForTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsForTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAverageGoalsForTotalValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsForTotalValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trAverageGoalsAgainstTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAverageGoalsAgainstTotal As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAverageGoalsAgainstTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsAgainstTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAverageGoalsAgainstTotalValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageGoalsAgainstTotalValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''MatchResultList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MatchResultList1 As Global.Predictathon.UserControls.Match.MatchResultList

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master, Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
