'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.Competition

    Partial Public Class CompetitionDetailEdit

        '''<summary>
        '''tblCompetitionDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCompetitionDetail As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblCompetitionName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCompetitionName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCompetitionName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompetitionName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnChange As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblPrependNameWithThe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrependNameWithThe As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkPrependNameWithThe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPrependNameWithThe As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnShowTeams control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnShowTeams As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dteStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteStartDate As Global.Predictathon.Web.UI.WebControls.DatePicker

        '''<summary>
        '''lblEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dteEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteEndDate As Global.Predictathon.Web.UI.WebControls.DatePicker

        '''<summary>
        '''lblDuplicateFixturesAllowed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDuplicateFixturesAllowed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkDuplicateFixturesAllowed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDuplicateFixturesAllowed As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDefaultToNeutralGround control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDefaultToNeutralGround As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkDefaultToNeutralGround control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDefaultToNeutralGround As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAllowTwoPointers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowTwoPointers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkAllowTwoPointers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowTwoPointers As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblOpenForRegistration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOpenForRegistration As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkOpenForRegistration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOpenForRegistration As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblRegistrationAvailableOnLoginPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRegistrationAvailableOnLoginPage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkRegistrationAvailableOnLoginPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRegistrationAvailableOnLoginPage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblShowInHallOfFame control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowInHallOfFame As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkShowInHallOfFame control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowInHallOfFame As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblEntranceFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEntranceFee As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEntranceFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEntranceFee As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPayPalPaymentAvailable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPayPalPaymentAvailable As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkPayPalPaymentAvailable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPayPalPaymentAvailable As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblImageFilename control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImageFilename As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtImageFilename control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtImageFilename As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInformation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInformation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSubmitDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmitDetails As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divSaveConfirmed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSaveConfirmed As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSaved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSaved As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master, Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
