'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.User

	Partial Public Class UserDetail

		'''<summary>
		'''UserProfile1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UserProfile1 As Global.Predictathon.UserControls.User.UserProfile

		'''<summary>
		'''UserStatistics1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UserStatistics1 As Global.Predictathon.UserControls.User.UserStatistics

		'''<summary>
		'''UserCompetitionLeagueHistory1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UserCompetitionLeagueHistory1 As Global.Predictathon.UserControls.User.UserCompetitionLeagueHistory

		'''<summary>
		'''UserPredictionList1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UserPredictionList1 As Global.Predictathon.UserControls.User.UserPredictionList

		'''<summary>
		'''UserLeagueTable1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UserLeagueTable1 As Global.Predictathon.UserControls.User.UserLeagueTable

		'''<summary>
		'''Master property.
		'''</summary>
		'''<remarks>
		'''Auto-generated property.
		'''</remarks>
		Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
			Get
				Return CType(MyBase.Master, Predictathon.Master.Main)
			End Get
		End Property
	End Class
End Namespace
