'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.User

    Partial Public Class UserDetailEdit

        '''<summary>
        '''rbUserDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbUserDetail As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbProfilePicture control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbProfilePicture As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''tblUserDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblUserDetail As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblForenames control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblForenames As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtForenames control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForenames As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSurname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSurname As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSurname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSurname As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEmailPredictionReminderDays control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailPredictionReminderDays As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEmailPredictionReminderDays control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailPredictionReminderDays As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEmailPredictionReminderDaysHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailPredictionReminderDaysHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChangePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChangePassword As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkChangePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkChangePassword As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPassword As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPassword As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trPassword2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPassword2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblConfirmPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConfirmPassword As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtConfirmPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtConfirmPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblFavouriteTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFavouriteTeam As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFavouriteTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFavouriteTeam As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLocation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblProfileText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProfileText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtProfileText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProfileText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trCanViewMessageboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trCanViewMessageboard As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCanViewMessageboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCanViewMessageboard As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkCanViewMessageboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCanViewMessageboard As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trCanViewHiddenMessageThreads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trCanViewHiddenMessageThreads As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCanViewHiddenMessageThreads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCanViewHiddenMessageThreads As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkCanViewHiddenMessageThreads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCanViewHiddenMessageThreads As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnSubmitUserDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmitUserDetails As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divSaveConfirmed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSaveConfirmed As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSaved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSaved As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ifImageUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifImageUpload As Global.System.Web.UI.HtmlControls.HtmlIframe

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master, Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
