'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.User

    Partial Public Class UserCompetitionRegistration

        '''<summary>
        '''hdnp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnp As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblCompetitionNameValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCompetitionNameValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStartDateValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDateValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEndDateValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDateValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRegistrationStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRegistrationStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''spnEntranceFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnEntranceFee As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblEntranceFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEntranceFee As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEntranceFeeValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEntranceFeeValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pCompetitionInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pCompetitionInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCompetitionInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCompetitionInformation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divEnterCompetition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEnterCompetition As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''btnEnterCompetition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEnterCompetition As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPayment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblPaymentRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentRequest As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentRequest2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentRequest2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pPaymentOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pPaymentOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rbPaymentCredit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbPaymentCredit As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbPayPal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbPayPal As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''pPaymentCredit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pPaymentCredit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblPaymentCreditCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentCreditCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPaymentCreditCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPaymentCreditCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSubmitPaymentCreditCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmitPaymentCreditCode As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pPayPal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pPayPal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''btnPayPal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPayPal As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''divRegistrationConfirmed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divRegistrationConfirmed As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''liKeepPredicting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liKeepPredicting As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''btnLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master, Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
