'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.User

    Partial Public Class UserLeagueTable

        '''<summary>
        '''UserLeagueTable1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserLeagueTable1 As Global.Predictathon.UserControls.User.UserLeagueTable

        '''<summary>
        '''RealLeagueTable1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RealLeagueTable1 As Global.Predictathon.UserControls.Competition.RealLeagueTable

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master, Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
