// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class Competition
{
    public Guid CompetitionID { get; set; }

    public string CompetitionName { get; set; } = null!;

    public bool PrependNameWithThe { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public bool DuplicateFixturesAllowed { get; set; }

    public bool OpenForRegistration { get; set; }

    public bool RegistrationAvailableOnLoginPage { get; set; }

    public bool ShowInHallOfFame { get; set; }

    public decimal EntranceFee { get; set; }

    public bool PayPalPaymentAvailable { get; set; }

    public string? Information { get; set; }

    public string? ImageFilename { get; set; }

    public bool DefaultToNeutralGround { get; set; }

    public bool AllowTwoPointers { get; set; }

    public virtual ICollection<HallOfFame> HallOfFame { get; set; } = new List<HallOfFame>();

    public virtual ICollection<Match> Match { get; set; } = new List<Match>();

    public virtual ICollection<PaymentCredit> PaymentCredit { get; set; } = new List<PaymentCredit>();

    public virtual ICollection<TeamCompetition> TeamCompetition { get; set; } = new List<TeamCompetition>();

    public virtual ICollection<Transaction> Transaction { get; set; } = new List<Transaction>();

    public virtual ICollection<UserCompetition> UserCompetition { get; set; } = new List<UserCompetition>();
}
