// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class Message
{
    public Guid MessageID { get; set; }

    public Guid MessageThreadID { get; set; }

    public Guid PostedByUserID { get; set; }

    public DateTime MessageDateTime { get; set; }

    public string? MessageContent { get; set; }

    public string? YouTubeVideoID { get; set; }

    public bool HasLinkedImage { get; set; }

    public int UserTotalMessageboardPosts { get; set; }

    public virtual ICollection<MessageReaction> MessageReaction { get; set; } = new List<MessageReaction>();

    public virtual MessageThread MessageThread { get; set; } = null!;

    public virtual User PostedByUser { get; set; } = null!;
}
