// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class PaymentCredit
{
    public Guid PaymentCreditID { get; set; }

    public string? ExpectedUsername { get; set; }

    public Guid ForCompetitionID { get; set; }

    public string UniquePaymentCode { get; set; } = null!;

    public bool CreditUsed { get; set; }

    public Guid? UsedByUserID { get; set; }

    public Guid IssuedByUserID { get; set; }

    public DateTime IssueDate { get; set; }

    public virtual Competition ForCompetition { get; set; } = null!;

    public virtual User IssuedByUser { get; set; } = null!;

    public virtual User? UsedByUser { get; set; }
}
