'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.Match
    
    Partial Public Class MatchDetail
        
        '''<summary>
        '''imgHomeTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgHomeTeam As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''litTeamNames control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTeamNames As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''imgAwayTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAwayTeam As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''lbl90Minutes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl90Minutes As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MatchDescriptionHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MatchDescriptionHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnMatchDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnMatchDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblMatchDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMatchDescription As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMatchDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMatchDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lnkEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkEdit As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''pnlSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSave As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''lblYourPrediction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblYourPrediction As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtHomeTeamGoals control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeTeamGoals As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtAwayTeamGoals control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAwayTeamGoals As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnSavePrediction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSavePrediction As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''lblPoints control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPoints As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblSaveProgress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSaveProgress As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''divKnockout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divKnockout As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblKnockout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblKnockout As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MatchPredictionList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MatchPredictionList1 As Global.Predictathon.UserControls.Match.MatchPredictionList
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master,Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
