'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.Match
    
    Partial Public Class MatchListAdmin
        
        '''<summary>
        '''lblSearchCriteria control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSearchCriteria As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''chkIncludePlayedMatches control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludePlayedMatches As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''tblAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAddNew As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''lblAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAdd As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlHomeTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHomeTeam As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlAwayTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAwayTeam As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''dteMatchDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteMatchDate As Global.Predictathon.Web.UI.WebControls.DatePicker
        
        '''<summary>
        '''tmeMatchTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tmeMatchTime As Global.Predictathon.Web.UI.WebControls.TimePicker
        
        '''<summary>
        '''lblNeutral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNeutral As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''chkNeutralGround control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNeutralGround As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''btnAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''txtHomeTeamTBC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeTeamTBC As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtAwayTeamTBC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAwayTeamTBC As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtMatchDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMatchDescription As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblKnockout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblKnockout As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''chkKnockout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkKnockout As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''trError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trError As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''gvMatch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvMatch As Global.Predictathon.Web.UI.WebControls.GridView
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master,Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
