'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.Match
    
    Partial Public Class MatchEdit
        
        '''<summary>
        '''imgHomeTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgHomeTeam As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''litTeamNames control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTeamNames As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''imgAwayTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAwayTeam As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''MatchDescriptionHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MatchDescriptionHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnMatchDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnMatchDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblMatchDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMatchDescription As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMatchDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMatchDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''dteMatchDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteMatchDate As Global.Predictathon.Web.UI.WebControls.DatePicker
        
        '''<summary>
        '''tmeMatchTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tmeMatchTime As Global.Predictathon.Web.UI.WebControls.TimePicker
        
        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master,Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
