'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages.Match
    
    Partial Public Class UserMatchPredictionList
        
        '''<summary>
        '''btnPreviousMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPreviousMonth As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''btnPreviousWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPreviousWeek As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''lblFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFrom As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''dteDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteDateFrom As Global.Predictathon.Web.UI.WebControls.DatePicker
        
        '''<summary>
        '''btnNextWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNextWeek As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''btnNextMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNextMonth As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''lstMatch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstMatch As Global.System.Web.UI.WebControls.ListView
        
        '''<summary>
        '''divKnockout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divKnockout As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblKnockout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblKnockout As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master,Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
