'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages

    Partial Public Class MainMenu

        '''<summary>
        '''UserStatistics1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserStatistics1 As Global.Predictathon.UserControls.User.UserStatistics

        '''<summary>
        '''UserCompetitionRegistrationList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserCompetitionRegistrationList1 As Global.Predictathon.UserControls.Competition.UserCompetitionRegistrationList

        '''<summary>
        '''UserMatchPredictionList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserMatchPredictionList1 As Global.Predictathon.UserControls.Match.UserMatchPredictionList

        '''<summary>
        '''UserMatchPredictionList2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserMatchPredictionList2 As Global.Predictathon.UserControls.Match.UserMatchPredictionList

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Predictathon.Master.Main
            Get
                Return CType(MyBase.Master, Predictathon.Master.Main)
            End Get
        End Property
    End Class
End Namespace
