'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls.User

	Partial Public Class UserCompetitionLeagueHistory

		'''<summary>
		'''divChart control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents divChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

		'''<summary>
		'''lblUsername control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''chtLeagueHistory control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chtLeagueHistory As Global.System.Web.UI.DataVisualization.Charting.Chart
	End Class
End Namespace
