'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls.User

    Partial Public Class UserProfile

        '''<summary>
        '''divPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPopup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgLarge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgLarge As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''divUserProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUserProfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnEditUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEditUser As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imgProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgProfile As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''pCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pCaption As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pProfileText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pProfileText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblProfileText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProfileText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pLocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLocation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLocationValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLocationValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pFavouriteTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pFavouriteTeam As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFavouriteTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFavouriteTeam As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFavouriteTeamValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFavouriteTeamValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pNoInfoAvailable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pNoInfoAvailable As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblNoInfoAvailable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoInfoAvailable As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
