'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls.User

    Partial Public Class UserLeagueTable

        '''<summary>
        '''hypGridTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypGridTitle As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''gvCompetitionUserLeagueTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvCompetitionUserLeagueTable As Global.Predictathon.Web.UI.WebControls.GridView
    End Class
End Namespace
