'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.UserControls.User

    Partial Public Class UserStatistics

        '''<summary>
        '''divUserStatistics control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUserStatistics As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnEditUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEditUser As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblLeaguePosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLeaguePosition As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLeaguePositionValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLeaguePositionValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPoints control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPoints As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPointsValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPointsValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trLastWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLastWeek As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''hypPointsLastWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPointsLastWeek As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblPointsLastWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPointsLastWeek As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPointsLastWeekValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPointsLastWeekValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trThisWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trThisWeek As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''hypPointsThisWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPointsThisWeek As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblPointsThisWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPointsThisWeek As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPointsThisWeekValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPointsThisWeekValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trNextPredictionDueIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trNextPredictionDueIn As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''hypUserMatchPredictionList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypUserMatchPredictionList1 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblNextPredictionDueIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNextPredictionDueIn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hypUserMatchPredictionList2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypUserMatchPredictionList2 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblNextPredictionDueInValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNextPredictionDueInValue As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
