'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Predictathon.Pages

    Partial Public Class Login

        '''<summary>
        '''lnkFavicon1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkFavicon1 As Global.System.Web.UI.HtmlControls.HtmlLink

        '''<summary>
        '''lnkFavicon2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkFavicon2 As Global.System.Web.UI.HtmlControls.HtmlLink

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''hdnCompetitionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnCompetitionID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''divLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divLogin As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkRememberMe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRememberMe As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnLogIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogIn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divPasswordReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPasswordReset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PasswordReset1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PasswordReset1 As Global.Predictathon.UserControls.User.PasswordReset

        '''<summary>
        '''lnkHidePasswordReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkHidePasswordReset As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblOpenForRegistration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOpenForRegistration As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNotOpenForRegistration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotOpenForRegistration As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptCompetitions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCompetitions As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblThree As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTwo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOne As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divRules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divRules As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Rules1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Rules1 As Global.Predictathon.UserControls.Rules.Rules
    End Class
End Namespace
