// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;

namespace Predictathon.Domain.Entities;

public partial class Announcement
{
    public int AnnouncementID { get; set; }

    public string Content { get; set; } = null!;

    public bool ShowOnLoginPage { get; set; }

    public bool ShowOnHomepage { get; set; }

    public string Severity { get; set; } = null!;

    public DateTime? ExpiryDateTimeUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public Guid CreatedByUserID { get; set; }
}
