// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class CompetitionSeries
{
    public Guid CompetitionSeriesID { get; set; }

    public string SeriesName { get; set; } = null!;

    public string ShortName { get; set; } = null!;

    public string? BadgeIcon { get; set; }

    public string? BadgeColour { get; set; }

    public int DisplayOrder { get; set; }

    public virtual ICollection<Competition> Competition { get; set; } = new List<Competition>();

    public virtual ICollection<HallOfFame> HallOfFame { get; set; } = new List<HallOfFame>();
}
