// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;

namespace Predictathon.Domain.Entities;

public partial class ErrorLog
{
    public int Id { get; set; }

    public string? Message { get; set; }

    public string? MessageTemplate { get; set; }

    public string? Level { get; set; }

    public DateTime TimeStampUtc { get; set; }

    public string? Exception { get; set; }

    public string? Properties { get; set; }
}
