// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;

namespace Predictathon.Domain.Entities;

public partial class FixtureChangeProposal
{
    public int FixtureChangeProposalID { get; set; }

    public Guid MatchID { get; set; }

    public DateTime PreviousMatchDateTime { get; set; }

    public DateTime ProposedMatchDateTime { get; set; }

    public DateTime DetectedAtUtc { get; set; }

    public string Status { get; set; } = null!;

    public DateTime? ResolvedAtUtc { get; set; }

    public virtual Match Match { get; set; } = null!;
}
