// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class HallOfFame
{
    public Guid HallOfFameID { get; set; }

    public Guid? CompetitionID { get; set; }

    public string? CompetitionName { get; set; }

    public string? Winner { get; set; }

    public Guid? WinnerUserID { get; set; }

    public string? SecondPlace { get; set; }

    public Guid? SecondPlaceUserID { get; set; }

    public string? ThirdPlace { get; set; }

    public Guid? ThirdPlaceUserID { get; set; }

    public DateOnly EndDate { get; set; }

    public string? ImageFilename { get; set; }

    public virtual Competition? Competition { get; set; }
}
