// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;

namespace Predictathon.Domain.Entities;

public partial class MatchLiveScore
{
    public Guid MatchID { get; set; }

    public int HomeTeamGoals { get; set; }

    public int AwayTeamGoals { get; set; }

    public string? Status { get; set; }

    public string Source { get; set; } = null!;

    public DateTime UpdatedDateTime { get; set; }

    public DateTime? LastPolledDateTime { get; set; }

    public Guid? UpdatedByUserID { get; set; }

    public virtual Match Match { get; set; } = null!;
}
