// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class Match
{
    public Guid MatchID { get; set; }

    public Guid CompetitionID { get; set; }

    public DateTime MatchDateTime { get; set; }

    public Guid? HomeTeamID { get; set; }

    public Guid? AwayTeamID { get; set; }

    public bool MatchPlayed { get; set; }

    public int? HomeTeamGoals { get; set; }

    public int? AwayTeamGoals { get; set; }

    public bool NeutralGround { get; set; }

    public string? HomeTeamTBC { get; set; }

    public string? AwayTeamTBC { get; set; }

    public string? Description { get; set; }

    public bool Knockout { get; set; }

    public int? ExternalMatchID { get; set; }

    public virtual Team? AwayTeam { get; set; }

    public virtual Competition Competition { get; set; } = null!;

    public virtual ICollection<FixtureChangeProposal> FixtureChangeProposal { get; set; } = new List<FixtureChangeProposal>();

    public virtual Team? HomeTeam { get; set; }

    public virtual MatchLiveScore? MatchLiveScore { get; set; }

    public virtual ICollection<Prediction> Prediction { get; set; } = new List<Prediction>();
}
