// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class MessageReaction
{
    public Guid MessageReactionID { get; set; }

    public Guid MessageID { get; set; }

    public Guid UserID { get; set; }

    public string ReactionId { get; set; } = null!;

    public string ReactionName { get; set; } = null!;

    public DateTime CreationDate { get; set; }

    public virtual Message Message { get; set; } = null!;
}
