// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class MessageThreadRead
{
    public int MessageThreadReadID { get; set; }

    public Guid UserID { get; set; }

    public Guid MessageThreadID { get; set; }

    public DateTime LastReadDateTime { get; set; }

    public virtual MessageThread MessageThread { get; set; } = null!;
}
