// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class MessageThread
{
    public Guid MessageThreadID { get; set; }

    public string? ThreadSubject { get; set; }

    public Guid StartedByUserID { get; set; }

    public DateTime StartedDateTime { get; set; }

    public bool HiddenFromPublic { get; set; }

    public virtual ICollection<Message> Message { get; set; } = new List<Message>();

    public virtual ICollection<MessageThreadRead> MessageThreadRead { get; set; } = new List<MessageThreadRead>();
}
