// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class PredictionHistory
{
    public int PredictionHistoryID { get; set; }

    public Guid PredictionID { get; set; }

    public int? HomeTeamGoals { get; set; }

    public int? AwayTeamGoals { get; set; }

    public DateTime PredictionDateTime { get; set; }
}
