// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class Team
{
    public Guid TeamID { get; set; }

    public string TeamName { get; set; } = null!;

    public string ShortName { get; set; } = null!;

    public string? ImageName { get; set; }

    public string? ExternalApiCode { get; set; }

    public virtual ICollection<Match> MatchAwayTeam { get; set; } = new List<Match>();

    public virtual ICollection<Match> MatchHomeTeam { get; set; } = new List<Match>();

    public virtual ICollection<TeamCompetition> TeamCompetition { get; set; } = new List<TeamCompetition>();
}
