// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class TeamCompetition
{
    public Guid TeamCompetitionID { get; set; }

    public Guid TeamID { get; set; }

    public Guid CompetitionID { get; set; }

    public virtual Competition Competition { get; set; } = null!;

    public virtual Team Team { get; set; } = null!;
}
