// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class Transaction
{
    public Guid TransactionID { get; set; }

    public Guid? CompetitionID { get; set; }

    public Guid? UserID { get; set; }

    public Guid? UserCompetitionID { get; set; }

    public string? Username { get; set; }

    public string? Password { get; set; }

    public string? EmailAddress { get; set; }

    public string? Forenames { get; set; }

    public string? Surname { get; set; }

    public decimal Amount { get; set; }

    public string? TransactionStatus { get; set; }

    public decimal? ActualPaymentAmount { get; set; }

    public string? PayPalTransactionID { get; set; }

    public decimal? PayPalFee { get; set; }

    public DateTime TransactionDateTime { get; set; }

    public bool? Failed { get; set; }

    public bool? ContainedInvalidData { get; set; }

    public string? Comments { get; set; }

    public virtual Competition? Competition { get; set; }

    public virtual User? User { get; set; }

    public virtual UserCompetition? UserCompetition { get; set; }
}
