// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class User
{
    public Guid UserID { get; set; }

    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public string? EmailAddress { get; set; }

    public string? Forenames { get; set; }

    public string? Surname { get; set; }

    public string? FavouriteTeam { get; set; }

    public string? Location { get; set; }

    public string? Caption { get; set; }

    public string? ProfileText { get; set; }

    public DateTime? LastLoginDateTime { get; set; }

    public bool MatchAdministrator { get; set; }

    public bool UserAdministrator { get; set; }

    public bool CompetitionAdministrator { get; set; }

    public bool ImageUploaded { get; set; }

    public DateTime? LastViewedMessageboard { get; set; }

    public int TotalMessageboardPosts { get; set; }

    public int? EmailPredictionReminderDays { get; set; }

    public bool CanViewHiddenMessageThreads { get; set; }

    public bool CanViewMessageboard { get; set; }

    public virtual ICollection<HallOfFame> HallOfFameSecondPlaceUser { get; set; } = new List<HallOfFame>();

    public virtual ICollection<HallOfFame> HallOfFameThirdPlaceUser { get; set; } = new List<HallOfFame>();

    public virtual ICollection<HallOfFame> HallOfFameWinnerUser { get; set; } = new List<HallOfFame>();

    public virtual ICollection<Message> Message { get; set; } = new List<Message>();

    public virtual ICollection<MessageReaction> MessageReaction { get; set; } = new List<MessageReaction>();

    public virtual ICollection<MessageThread> MessageThread { get; set; } = new List<MessageThread>();

    public virtual ICollection<MessageThreadRead> MessageThreadRead { get; set; } = new List<MessageThreadRead>();

    public virtual ICollection<PaymentCredit> PaymentCreditIssuedByUser { get; set; } = new List<PaymentCredit>();

    public virtual ICollection<PaymentCredit> PaymentCreditUsedByUser { get; set; } = new List<PaymentCredit>();

    public virtual ICollection<Prediction> Prediction { get; set; } = new List<Prediction>();

    public virtual ICollection<Transaction> Transaction { get; set; } = new List<Transaction>();

    public virtual ICollection<UserCompetition> UserCompetition { get; set; } = new List<UserCompetition>();
}
