// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class UserCompetitionLeagueHistory
{
    public Guid UserCompetitionLeagueHistoryID { get; set; }

    public Guid UserCompetitionID { get; set; }

    public DateOnly Date { get; set; }

    public int LeaguePosition { get; set; }

    public int Score { get; set; }

    public decimal AverageGoalDifference { get; set; }

    public int TotalGoalDifference { get; set; }
}
