// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace Predictathon.Domain.Entities;

public partial class UserCompetition
{
    public Guid UserCompetitionID { get; set; }

    public Guid UserID { get; set; }

    public Guid CompetitionID { get; set; }

    public decimal AmountPaid { get; set; }

    public string? PaymentProvider { get; set; }

    public Guid? PaymentCreditID { get; set; }

    public bool IsDefaultCompetition { get; set; }

    public DateTime? LastEmailReminderSent { get; set; }

    public virtual Competition Competition { get; set; } = null!;

    public virtual ICollection<Transaction> Transaction { get; set; } = new List<Transaction>();
}
